# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
# - GHCVER=6.12.3
 - CABALVER=1.16 GHCVER=7.4.2 GHCOPTS="-Werror"
 - CABALVER=1.18 GHCVER=7.6.3 GHCOPTS="-Werror"
 - CABALVER=1.18 GHCVER=7.8.4 GHCOPTS="-Werror" # see note on Alex/Happy
 - CABALVER=1.22 GHCVER=7.10.1 GHCOPTS=""

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-$CABALVER update
 - cabal-$CABALVER install --only-dependencies --enable-tests

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal-$CABALVER configure --enable-tests -v2  # -v2 provides useful information for debugging
 - cabal-$CABALVER build --ghc-options="$GHCOPTS"  # this builds all libraries and executables (including tests/benchmarks)
 - cabal-$CABALVER check
